package APKDetailViewer3;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;

import symbolic.Expression;

/**
 *
 * @author zhenxu
 */
public class ShowcaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public ShowcaseFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        apkPathField = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();
        initButton = new javax.swing.JButton();
        newCheckBox = new javax.swing.JCheckBox();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        methodBox = new javax.swing.JComboBox<String>();
        classBox = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        pathSummaryBox = new javax.swing.JComboBox<String>();
        analyzeButton = new javax.swing.JButton();
        jSplitPane3 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        executionPane = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        smaliClassBox = new javax.swing.JComboBox();
        smaliPane = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        symbolicList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        constraintList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        testerPane = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        selectedSymList = new javax.swing.JList<Expression>();
        jScrollPane7 = new javax.swing.JScrollPane();
        selectedConList = new javax.swing.JList<Expression>();
        jPanel3 = new javax.swing.JPanel();
        checkButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        dataMenu = new javax.swing.JMenu();
        clearMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APK Detail Viewer");

        jLabel3.setText("  Info:");

        infoLabel.setText("Welcome");

        jLabel1.setText("  EnterURL: ");

        openButton.setText("Open");

        initButton.setText("Init");

        newCheckBox.setText("New");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(apkPathField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apkPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openButton)
                    .addComponent(newCheckBox))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Basic", jPanel6);

        jLabel5.setText("  Class:");
        jLabel5.setPreferredSize(new java.awt.Dimension(46, 20));

        jLabel6.setText("  Method:");
        jLabel6.setPreferredSize(new java.awt.Dimension(46, 20));

        methodBox.setToolTipText("Choose a method");

        classBox.setToolTipText("Choose a class");

        jLabel2.setText("  Path:");

        analyzeButton.setText("Analyze");

        jSplitPane3.setDividerSize(3);
        jSplitPane3.setResizeWeight(0.5);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary Info"));

        jScrollPane1.setBorder(null);

        executionPane.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(executionPane);

        jTabbedPane1.addTab("Log", jScrollPane1);

        jPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smaliClassBox, 0, 409, Short.MAX_VALUE)
            .addComponent(smaliPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(smaliClassBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smaliPane, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Smali", jPanel1);

        symbolicList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(symbolicList);

        jTabbedPane1.addTab("Symbolic", jScrollPane3);

        constraintList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(constraintList);

        jTabbedPane1.addTab("Constraint", jScrollPane2);

        jSplitPane3.setLeftComponent(jTabbedPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Solver Test"));

        selectedSymList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(selectedSymList);

        testerPane.addTab("Symbolics", jScrollPane6);

        selectedConList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(selectedConList);

        testerPane.addTab("Constraints", jScrollPane7);

        checkButton.setText("Check");

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane5.setViewportView(resultArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(checkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkButton))
        );

        testerPane.addTab("Result", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testerPane)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testerPane, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathSummaryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(methodBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(analyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jSplitPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(methodBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzeButton))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pathSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane3))
        );

        jTabbedPane2.addTab("Symbolic Execution", jPanel4);

        dataMenu.setText("Data");

        clearMenuItem.setText("Clear Cache");
        dataMenu.add(clearMenuItem);

        jMenuBar1.add(dataMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane2)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoLabel))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                                                               
    
    
    
    void addTextPane(String text, List<String> toHightlight){
 	   JTextPane pane = new JTextPane();
 	   pane.setText(text);
 	   pane.setMinimumSize(new Dimension(300,400));
 	   for (String line : toHightlight) {
 			int start = text.indexOf(line);
 			if(start >= 0){
 				try {
 					int end = text.indexOf('\n', text.indexOf('\n', start)+1);
 					pane.getHighlighter().addHighlight(start, end, primaryHightlight);
 				} catch (BadLocationException e) {
 					e.printStackTrace();
 				}
 			}else{
 				System.out.println("Fail to find: "+line);
 			}
 	   }
 	   pane.setOpaque(true);
 	   pane.setVisible(true);
 	   this.textList.add(pane);
    }
    
    void chooseTextPane(int index, String toHightlight){
 	   JTextPane pane = this.textList.get(index);
 	   if(pane == null) return;
 	   smaliPane.setViewportView(pane);
 	   if(toHightlight != null){
 		   if(this.previousIndex >= 0 && this.previousIndex < this.textList.size()){
 			  JTextPane pPane =  textList.get(previousIndex);
 			  pPane.getHighlighter().removeHighlight(previousTag);
 		   }
 		   
 		   String text = pane.getText();
 		   int start = text.indexOf(toHightlight);
 		   if(start >= 0){
 			   int end = text.indexOf('\n', text.indexOf('\n', start)+1);
 			   try {
 				   previousTag = pane.getHighlighter().addHighlight(start, end, secondaryHight);
 				   this.previousIndex = index;
 			   } catch (BadLocationException e) {
 				   e.printStackTrace();
 				   this.previousIndex = -1;
 				   this.previousTag = null;
 			   }
 		   }else{
 			   this.previousIndex = -1;
 			   this.previousTag = null;
 		   }
 	   }else{ 
 		  smaliPane.getViewport().setViewPosition(new Point(0,0)); 
 		   if(this.textList.isEmpty()){
 			   this.previousIndex = -1;
 			   this.previousTag = null;
 		   }
 	   }
    }
    
    void clearTextPane(){
 	   this.textList.clear();
    }
    
    // Variables declaration - do not modify                     
    javax.swing.JButton analyzeButton;
    javax.swing.JTextField apkPathField;
    javax.swing.JButton checkButton;
    javax.swing.JComboBox<String> classBox;
    javax.swing.JMenuItem clearMenuItem;
    javax.swing.JList<Expression> constraintList;
    javax.swing.JList<String> executionPane;
    javax.swing.JLabel infoLabel;
    javax.swing.JButton initButton;
    javax.swing.JComboBox<String> methodBox;
    javax.swing.JCheckBox newCheckBox;
    javax.swing.JButton openButton;
    javax.swing.JComboBox<String> pathSummaryBox;
    javax.swing.JTextArea resultArea;
    javax.swing.JList<Expression> selectedConList;
    javax.swing.JList<Expression> selectedSymList;
    javax.swing.JComboBox<String> smaliClassBox;
    javax.swing.JScrollPane smaliPane;
    javax.swing.JList<Expression> symbolicList;
    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu dataMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane testerPane;
    // End of variables declaration         
    
    private int previousIndex = -1;
    private Object previousTag = null;
    private List<JTextPane> textList = new ArrayList<JTextPane>();
    private DefaultHighlighter.DefaultHighlightPainter primaryHightlight = 
 	        new DefaultHighlighter.DefaultHighlightPainter(Color.GREEN);

    private DefaultHighlighter.DefaultHighlightPainter secondaryHight = 
 	        new DefaultHighlighter.DefaultHighlightPainter(Color.RED);
}
